Repository rahulguptalmao42069/SortingAlgos, pull requests merged in 2022-10, with the labels that each got.

#1 Selection sort done in c++
  Selection.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#2 All in one sorting algorithms
  Sorts.cpp
Labels: enhancement, hacktoberfest-accepted

#3 Basic Mathematics for programmers
  Maths4Programmers.cpp
Labels: good first issue, hacktoberfest-accepted
